// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/infrastructure/grpc/proto/product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Producto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,3,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Precio        float64                `protobuf:"fixed64,4,opt,name=precio,proto3" json:"precio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producto) Reset() {
	*x = Producto{}
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producto) ProtoMessage() {}

func (x *Producto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producto.ProtoReflect.Descriptor instead.
func (*Producto) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *Producto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Producto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Producto) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Producto) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

type ProductId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProductosList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Producto            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductosList) Reset() {
	*x = ProductosList{}
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductosList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductosList) ProtoMessage() {}

func (x *ProductosList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductosList.ProtoReflect.Descriptor instead.
func (*ProductosList) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductosList) GetItems() []*Producto {
	if x != nil {
		return x.Items
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_grpc_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_grpc_proto_product_proto_rawDescGZIP(), []int{3}
}

var File_internal_infrastructure_grpc_proto_product_proto protoreflect.FileDescriptor

const file_internal_infrastructure_grpc_proto_product_proto_rawDesc = "" +
	"\n" +
	"0internal/infrastructure/grpc/proto/product.proto\x12\aproduct\"l\n" +
	"\bProducto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x03 \x01(\tR\vdescripcion\x12\x16\n" +
	"\x06precio\x18\x04 \x01(\x01R\x06precio\"\x1b\n" +
	"\tProductId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\rProductosList\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.product.ProductoR\x05items\"\a\n" +
	"\x05Empty2\xff\x01\n" +
	"\x0eProductService\x12.\n" +
	"\x06Create\x12\x11.product.Producto\x1a\x11.product.Producto\x12,\n" +
	"\x03Get\x12\x12.product.ProductId\x1a\x11.product.Producto\x12.\n" +
	"\x06Update\x12\x11.product.Producto\x1a\x11.product.Producto\x12/\n" +
	"\x06Delete\x12\x12.product.ProductId\x1a\x11.product.Producto\x12.\n" +
	"\x04List\x12\x0e.product.Empty\x1a\x16.product.ProductosListB$Z\"internal/infrastructure/grpc/pb;pbb\x06proto3"

var (
	file_internal_infrastructure_grpc_proto_product_proto_rawDescOnce sync.Once
	file_internal_infrastructure_grpc_proto_product_proto_rawDescData []byte
)

func file_internal_infrastructure_grpc_proto_product_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_grpc_proto_product_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_grpc_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_infrastructure_grpc_proto_product_proto_rawDesc), len(file_internal_infrastructure_grpc_proto_product_proto_rawDesc)))
	})
	return file_internal_infrastructure_grpc_proto_product_proto_rawDescData
}

var file_internal_infrastructure_grpc_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_infrastructure_grpc_proto_product_proto_goTypes = []any{
	(*Producto)(nil),      // 0: product.Producto
	(*ProductId)(nil),     // 1: product.ProductId
	(*ProductosList)(nil), // 2: product.ProductosList
	(*Empty)(nil),         // 3: product.Empty
}
var file_internal_infrastructure_grpc_proto_product_proto_depIdxs = []int32{
	0, // 0: product.ProductosList.items:type_name -> product.Producto
	0, // 1: product.ProductService.Create:input_type -> product.Producto
	1, // 2: product.ProductService.Get:input_type -> product.ProductId
	0, // 3: product.ProductService.Update:input_type -> product.Producto
	1, // 4: product.ProductService.Delete:input_type -> product.ProductId
	3, // 5: product.ProductService.List:input_type -> product.Empty
	0, // 6: product.ProductService.Create:output_type -> product.Producto
	0, // 7: product.ProductService.Get:output_type -> product.Producto
	0, // 8: product.ProductService.Update:output_type -> product.Producto
	0, // 9: product.ProductService.Delete:output_type -> product.Producto
	2, // 10: product.ProductService.List:output_type -> product.ProductosList
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_grpc_proto_product_proto_init() }
func file_internal_infrastructure_grpc_proto_product_proto_init() {
	if File_internal_infrastructure_grpc_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_infrastructure_grpc_proto_product_proto_rawDesc), len(file_internal_infrastructure_grpc_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_grpc_proto_product_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_grpc_proto_product_proto_depIdxs,
		MessageInfos:      file_internal_infrastructure_grpc_proto_product_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_grpc_proto_product_proto = out.File
	file_internal_infrastructure_grpc_proto_product_proto_goTypes = nil
	file_internal_infrastructure_grpc_proto_product_proto_depIdxs = nil
}
